### ISSUE TITLE
Curl 26 error

### ISSUE THREAD

**Issue by CHJ85** [djaman/djaman-reomver#2]
What does this mean?
"curl: (26) Failed to open/read local data from file/application
DJAman-Remover Says:-the curl command failed with: 26 "

And how come I can't just type in ./djaman-remover.sh /path/to/input /path/to/output? I hate having to go through all these options.

**Comment by djaman** [comment]
The error message "curl: (26) Failed to open/read local data from file/application" indicates that the curl command was unable to read the input file specified in the API call. This could be due to a few reasons, such as the file not existing, incorrect file path, or incorrect permissions for the file. To resolve this issue, you should check that the input file path is correct and that the file exists and has the correct permissions.

As for why you can't just type "./djaman-remover.sh /path/to/input /path/to/output," it's because the script is designed to prompt the user for input and output paths as well as provide options for using the tool. If you want to use the tool with a single command, you could modify the script to accept command-line arguments instead of prompting the user for input

**Comment by CHJ85** [comment]
Okay, thank you for your help.

**Comment by djaman** [comment]
Issues solve
